.\" lat(1) manpage
.\"
.\" Copyright (C) 2004, 2005 MMG Security, Inc.
.\"
.TH lat "1" "May 2005" "lat" "Linux User's Manual"
.SH NAME
lat \- LDAP Administration Tool
.SH SYNOPSIS
.B lat
[\fIoptions\fR]
.SH DESCRIPTION
.PP
.BR lat ,
stands for LDAP Administration Tool. The tool allows you to browse 
LDAP-based directories and add/edit/delete entries contained within. 
It can store profiles for quick access to different servers. There are 
also different views available such as Users, Groups and Hosts which 
allow you to easily manage objects without having to deal with the 
intricacies of LDAP.
.SH OPTIONS
.BR lat
has few options, they are listed below.
.TP
.B -d, --debug
Run the program with debugging code turned on.
.TP
.B -h, --help
Print the program usage and exit.
.TP
.B -v, --version
Print the program version and exit.
.SH FILES
.BR $HOME/.lat/profiles.xml
.TP
Contains the users saved connection profiles.  There is no password 
information held in the files;  Passwords are stored in the users
GNOME keyring database.
.TP
.BR $HOME/.lat/plugins.state
.TP
Contains the user configuration for LAT plugins
.TP
.BR $HOME/.lat/profiles.xml
.TP
Contains information on user connection profiles
.TP
.BR $HOME/.lat/templates.dat
.TP
Contains information on the users custom templates.
.SH AUTHOR
Loren Bandiera <lorenb@mmgsecurity.com>
.SH "REPORTING BUGS"
Report bugs to http://dev.mmgsecurity.com/bugs/
.SH COPYRIGHT
Copyright \(co 2005 MMG Security, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
