// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GnomeKeyring {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum AttributeType {

		String,
		Uint32,
	}
#endregion
}
