// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GnomeKeyringSharp {

	using System;

#region Autogenerated code
	[GLib.CDeclCallback]
	internal delegate void OperationGetListCallbackNative(int result, IntPtr list, IntPtr data);

	internal class OperationGetListCallbackWrapper {

		public void NativeCallback (int result, IntPtr list, IntPtr data)
		{
			GnomeKeyring.Result _arg0 = (GnomeKeyring.Result) result;
			GLib.List _arg1 = new GLib.List(list);
			managed ( _arg0,  _arg1);
		}

		internal OperationGetListCallbackNative NativeDelegate;
		GnomeKeyring.OperationGetListCallback managed;

		public OperationGetListCallbackWrapper (GnomeKeyring.OperationGetListCallback managed)
		{
			this.managed = managed;
			if (managed != null)
				NativeDelegate = new OperationGetListCallbackNative (NativeCallback);
		}

		public static GnomeKeyring.OperationGetListCallback GetManagedDelegate (OperationGetListCallbackNative native)
		{
			if (native == null)
				return null;
			OperationGetListCallbackWrapper wrapper = (OperationGetListCallbackWrapper) native.Target;
			if (wrapper == null)
				return null;
			return wrapper.managed;
		}
	}
#endregion
}
