// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GnomeKeyring {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[StructLayout(LayoutKind.Sequential)]
	public struct NetworkPasswordData {

		public string Keyring;
		public uint ItemId;
		public string Protocol;
		public string Server;
		public string Object;
		public string Authtype;
		public uint Port;
		public string User;
		public string Domain;
		public string Password;

		public static GnomeKeyring.NetworkPasswordData Zero = new GnomeKeyring.NetworkPasswordData ();

		public static GnomeKeyring.NetworkPasswordData New(IntPtr raw) {
			if (raw == IntPtr.Zero) {
				return GnomeKeyring.NetworkPasswordData.Zero;
			}
			GnomeKeyring.NetworkPasswordData self = new GnomeKeyring.NetworkPasswordData();
			self = (GnomeKeyring.NetworkPasswordData) Marshal.PtrToStructure (raw, self.GetType ());
			return self;
		}

//		private static GLib.GType GType {
//			get { return GLib.GType.Pointer; }
//		}
#endregion
	}
}
