// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GnomeKeyring {

	using System;

	public delegate void OperationGetIntCallback(GnomeKeyring.Result result, uint val);

}
