// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GnomeKeyring {

	using System;

	public delegate void OperationGetListCallback(GnomeKeyring.Result result, GLib.List list);

}
